export default [
  {
    tournamentname: 'Grappling Industries',
    date: '2018-01-27T05:00:00.000Z',
    state: 'NY',
    location: 'Lake George/SS',
    price: 79,
    link: 'http://grapplingindustries.com/lakegeorge2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-01-27T05:00:00.000Z',
    state: 'CA',
    location: 'San Jose',
    price: 79,
    link: 'http://grapplingindustries.com/sanjose2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-03T05:00:00.000Z',
    state: 'OR',
    location: 'Portland',
    price: 79,
    link: 'http://grapplingindustries.com/portland2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-03T05:00:00.000Z',
    state: 'OH',
    location: 'Cleveland',
    price: 79,
    link: 'http://grapplingindustries.com/cleveland2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-10T05:00:00.000Z',
    state: 'ID',
    location: 'Boise',
    price: 79,
    link: 'http://grapplingindustries.com/boise2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-11T05:00:00.000Z',
    state: 'MO',
    location: 'Springfield',
    price: 79,
    link: 'http://grapplingindustries.com/missouri2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-17T05:00:00.000Z',
    state: 'UT',
    location: 'Salt Lake City',
    price: 79,
    link: 'http://grapplingindustries.com/saltlakecity2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-18T05:00:00.000Z',
    state: 'MI',
    location: 'Milwaukee',
    price: 79,
    link: 'http://grapplingindustries.com/milwaukee2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-24T05:00:00.000Z',
    state: 'SC',
    location: 'SC vs. NC (York, SC)',
    price: 79,
    link: 'http://grapplingindustries.com/carolinas/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-02-24T05:00:00.000Z',
    state: 'IA',
    location: 'Des Moines',
    price: 79,
    link: 'http://grapplingindustries.com/desmoines2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-03T05:00:00.000Z',
    state: 'OH',
    location: 'Columbus',
    price: 79,
    link: 'http://grapplingindustries.com/arnoldclassic/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-10T05:00:00.000Z',
    state: 'MA',
    location: 'Boston',
    price: 79,
    link: 'http://grapplingindustries.com/boston2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-10T05:00:00.000Z',
    state: 'MN',
    location: 'Minneapolis',
    price: 79,
    link: 'http://grapplingindustries.com/minneapolis2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-17T04:00:00.000Z',
    state: 'MI',
    location: 'Detroit',
    price: 79,
    link: 'http://grapplingindustries.com/detroit2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-17T04:00:00.000Z',
    state: 'MD',
    location: 'Frederick',
    price: 79,
    link: 'http://grapplingindustries.com/maryland2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-24T04:00:00.000Z',
    state: 'NY',
    location: 'Manhattan',
    price: 79,
    link: 'http://grapplingindustries.com/manhattan2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-03-24T04:00:00.000Z',
    state: 'KS',
    location: 'Kansas City (outside)',
    price: 79,
    link: 'http://grapplingindustries.com/kansascity2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-04-14T04:00:00.000Z',
    state: 'NV',
    location: 'Las Vegas',
    price: 79,
    link: 'http://grapplingindustries.com/lasvegas2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-04-14T04:00:00.000Z',
    state: 'OK',
    location: 'Oklahoma City',
    price: 79,
    link: 'http://grapplingindustries.com/okc2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-04-21T04:00:00.000Z',
    state: 'IL',
    location: 'Chicago',
    price: 79,
    link: 'http://grapplingindustries.com/chicago2018/',
    type: 'Points',
  },
  {
    tournamentname: 'Grappling Industries',
    date: '2018-04-21T04:00:00.000Z',
    state: 'TX',
    location: 'San Antonio',
    price: 79,
    link: 'http://grapplingindustries.com/sanantonio2018/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-01-28T05:00:00.000Z',
    state: 'CA',
    location: 'LA International Open',
    price: '$104/119',
    link:
      'http://ibjjf.com/championship/los-angeles-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-02-03T05:00:00.000Z',
    state: 'GA',
    location: 'Atlanta Winter International Open',
    link:
      'http://ibjjf.com/championship/atlanta-winter-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-02-11T05:00:00.000Z',
    state: 'TX',
    location: 'Houston International Open',
    link: 'http://ibjjf.com/championship/houston-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-02-18T05:00:00.000Z',
    state: 'CA',
    location: 'Kids Pan Championship - Long Beach, CA',
    price: '$89/90',
    link: 'http://ibjjf.com/championship/pan-kids-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-02-25T05:00:00.000Z',
    state: 'CA',
    location: 'San Francisco International Open',
    price: '$104/119',
    link:
      'http://ibjjf.com/championship/san-francisco-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-03-07T05:00:00.000Z',
    state: 'CA',
    location: 'Pan Jiu Jitsu Championship - Irvine, CA',
    price: '$99/119/134',
    link: 'http://ibjjf.com/championship/pan-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-03-24T04:00:00.000Z',
    state: 'IL',
    location: 'Chicago Spring International Open',
    price: '$99/120',
    link:
      'http://ibjjf.com/championship/chicago-spring-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-03-25T04:00:00.000Z',
    state: 'IL',
    location: 'Chicago Spring Kids International Open',
    price: '$89/90',
    link:
      'http://ibjjf.com/championship/chicago-spring-kids-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '         4/7-8/2018',
    state: 'MD',
    location:
      'Washington, DC Spring International Open Gi/No Gi - Hyattsville, MD',
    price: 129,
    link:
      'http://ibjjf.com/championship/washington-dc-spring-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-04-07T04:00:00.000Z',
    state: 'CA',
    location: 'San Jose International Open Gi/No Gi - Saratoga CA',
    price: 119,
    link:
      'http://ibjjf.com/championship/san-jose-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-04-14T04:00:00.000Z',
    state: 'MA',
    location: 'Boston International Open',
    price: 119,
    link:
      'http://ibjjf.com/championship/boston-spring-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '     4/21-22/2018',
    state: 'NY',
    location: 'New York Spring International Open Gi/No Gi',
    price: 123,
    link:
      'http://ibjjf.com/championship/new-york-spring-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '     4/21-22/2018',
    location: 'Denver International Open Gi/No Gi',
    price: 119,
    link: 'http://ibjjf.com/championship/denver-international-open-jiu-jitsu/',
  },
  {
    tournamentname: 'IBJJF',
    date: '     4/28-29/2018',
    state: 'TX',
    location: 'Dallas Spring International Open Gi/No Gi',
    price: 119,
    link:
      'http://ibjjf.com/championship/dallas-spring-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-05-05T04:00:00.000Z',
    state: 'GA',
    location: 'Atlanta Spring International Open',
    price: 119,
    link:
      'http://ibjjf.com/championship/atlanta-spring-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-05-12T04:00:00.000Z',
    state: 'FL',
    location: 'Miami Spring International Open',
    price: 119,
    link:
      'http://ibjjf.com/championship/miami-spring-international-open-jiu-jitsu/',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-05-12T04:00:00.000Z',
    state: 'CA',
    location: 'San Diego Spring International Open',
    price: 119,
    link:
      'http://ibjjf.com/championship/san-diego-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-05-31T04:00:00.000Z',
    state: 'CA',
    location: 'World IBJJF Jiu-Jitsu Championship - Long Beach, CA',
    price: 145,
    link: 'http://ibjjf.com/championship/world-master-ibjjf-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '6/28-30/2018',
    state: 'NV',
    location: 'American National Jiu-Jitsu Championship',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-06-30T04:00:00.000Z',
    state: 'NV',
    location: 'American National Kids Jiu-Jitsu Championship',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '7/21-22/2018',
    state: 'TX',
    location: 'Austin International Open',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-07-28T04:00:00.000Z',
    state: 'FL',
    location: 'Orlando International Open',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '     8/22-25/2018',
    state: 'CA',
    location: 'World Masters Jiu Jitsu Championship - Las Vegas, NV',
    price: '$108/130/145',
    link: 'http://ibjjf.com/championship/world-master-ibjjf-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '     8/22-23/2018',
    state: 'NV',
    location: 'Las Vegas Summer International Open',
    price: 130,
    link:
      'http://ibjjf.com/championship/las-vegas-summer-international-open-jiu-jitsu/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '     8/23-24/2018',
    state: 'NV',
    location: 'International Novice Jiu-Jitsu Championship – Las Vegas',
    price: 130,
    link:
      'http://ibjjf.com/championship/international-novice-jiu-jitsu-championship-las-vegas/',
    type: 'Points',
  },
  {
    tournamentname: 'IBJJF',
    date: '2018-08-25T04:00:00.000Z',
    state: 'NV',
    location: 'Kids International Jiu-Jitsu Championship – Las Vegas',
    price: 99,
    link:
      'http://ibjjf.com/championship/kids-international-jiu-jitsu-championship-las-vegas/',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-01-27T05:00:00.000Z',
    state: 'OH',
    location: 'Ohio Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/602',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-03T05:00:00.000Z',
    state: 'PA',
    location: 'Philadelphia Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/603',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-03T05:00:00.000Z',
    state: 'TX',
    location: 'Houston Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/604',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-10T05:00:00.000Z',
    state: 'NV',
    location: 'Vegas Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/605',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-17T05:00:00.000Z',
    state: 'MA',
    location: 'Boston Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/606',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-17T05:00:00.000Z',
    state: 'AZ',
    location: 'Phoenix Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/607',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-24T05:00:00.000Z',
    state: 'LA',
    location: 'New Orleans Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/608',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-02-24T05:00:00.000Z',
    state: 'OR',
    location: 'Oregon Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/609',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-03T05:00:00.000Z',
    state: 'CA',
    location: 'San Jose Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/610',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-03T05:00:00.000Z',
    state: 'NY',
    location: 'Albany Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/611',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-10T05:00:00.000Z',
    state: 'CA',
    location: 'San Diego Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/612',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-17T04:00:00.000Z',
    state: 'FL',
    location: 'Orlando Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/613',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-17T04:00:00.000Z',
    state: 'CO',
    location: 'Colorado Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/615',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-24T04:00:00.000Z',
    state: 'TN',
    location: 'Nashville Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/616',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-03-24T04:00:00.000Z',
    state: 'UT',
    location: 'Salt Lake City Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/617',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-04-07T04:00:00.000Z',
    state: 'TX',
    location: 'San Antonio Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/618',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-04-14T04:00:00.000Z',
    state: 'PA',
    location: 'Pittsburgh',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/619',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-04-14T04:00:00.000Z',
    state: 'HI',
    location: 'Pacific Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/620',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-04-21T04:00:00.000Z',
    state: 'GA',
    location: 'Atlanta Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/621',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-04-28T04:00:00.000Z',
    state: 'NJ',
    location: 'World Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/622',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-05-05T04:00:00.000Z',
    state: 'TX',
    location: 'Dallas Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/623',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-05-12T04:00:00.000Z',
    state: 'RI',
    location: 'East Coast Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/625',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-05-12T04:00:00.000Z',
    state: 'MN',
    location: 'Minnesota Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/629',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-05-19T04:00:00.000Z',
    state: 'IL',
    location: 'Chicago Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/624',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-06-02T04:00:00.000Z',
    state: 'MO',
    location: 'St. Louis Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/630',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-06-09T04:00:00.000Z',
    state: 'FL',
    location: 'Jacksonville Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/631',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-06-16T04:00:00.000Z',
    state: 'NC',
    location: 'Charlotte Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/632',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-06-23T04:00:00.000Z',
    state: 'TX',
    location: 'Texas Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/633',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-06-23T04:00:00.000Z',
    state: 'VA',
    location: 'Virginia Beach Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/634',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-06-30T04:00:00.000Z',
    state: 'NM',
    location: 'Albuquerque Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/635',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-07-07T04:00:00.000Z',
    state: 'FL',
    location: 'Tampa Championship',
    price: 85,
    link: 'http://nagafighter.com/index.php?module=eventinformationpage/636',
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-07-14T04:00:00.000Z',
    state: 'OH',
    location: 'Cincinnati Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-07-14T04:00:00.000Z',
    state: 'CT',
    location: 'Connecticut Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '     7/21-22/2018',
    state: 'AL',
    location: 'U.S. Nationals',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '         8/4-5/2018',
    state: 'NJ',
    location: 'Battle at the Beach',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-08-11T04:00:00.000Z',
    state: 'TX',
    location: 'Austin Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-08-18T04:00:00.000Z',
    state: 'NV',
    location: 'West Coast Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-08-18T04:00:00.000Z',
    state: 'SC',
    location: 'Myrtle Beach Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-08-25T04:00:00.000Z',
    state: 'AZ',
    location: 'Arizona Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-09-08T04:00:00.000Z',
    state: 'CA',
    location: 'San Diego Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-09-15T04:00:00.000Z',
    state: 'CA',
    location: 'Norcal Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-09-15T04:00:00.000Z',
    state: 'NY',
    location: 'New York Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-09-22T04:00:00.000Z',
    state: 'UT',
    location: 'Utah Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-09-29T04:00:00.000Z',
    state: 'WA',
    location: 'Washington Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-10-06T04:00:00.000Z',
    state: 'GA',
    location: 'NAGA Georgia',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-10-06T04:00:00.000Z',
    state: 'PA',
    location: 'Pennsylvania Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-10-13T04:00:00.000Z',
    state: 'TX',
    location: 'Lone Star Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-10-13T04:00:00.000Z',
    state: 'RI',
    location: 'New England Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-10-20T04:00:00.000Z',
    state: 'LA',
    location: 'Louisiana Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-10-27T04:00:00.000Z',
    state: 'TN',
    location: 'Tennessee Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-11-03T04:00:00.000Z',
    state: 'NC',
    location: 'North Carolina Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-11-10T05:00:00.000Z',
    state: 'IL',
    location: 'Illinois Championship',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '2018-12-01T05:00:00.000Z',
    state: 'FL',
    location: 'Pan American',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'NAGA',
    date: '             12/8-9/2018  ',
    state: 'TX',
    location: 'World Jiu Jitsu',
    price: 85,
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-02-03T05:00:00.000Z',
    state: 'IL',
    location: 'Chicago',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/532.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-02-10T05:00:00.000Z',
    state: 'NY',
    location: 'Long Island',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/522.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-02-17T05:00:00.000Z',
    state: 'NJ',
    location: 'Monroe Township',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/523.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-02-24T05:00:00.000Z',
    state: 'GA',
    location: 'McDonough',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/524.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-03-03T05:00:00.000Z',
    state: 'FL',
    location: 'Orlando',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/525.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-03-10T05:00:00.000Z',
    state: 'TX',
    location: 'Houston',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/526.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-03-17T04:00:00.000Z',
    state: 'TX',
    location: 'Dallas',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/527.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-03-24T04:00:00.000Z',
    state: 'LA',
    location: 'New Orleans',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/528.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-03-21T04:00:00.000Z',
    state: 'FL',
    location: 'Miami',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/554.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-04-07T04:00:00.000Z',
    state: 'SC',
    location: 'Spartanburg',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/529.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-04-14T04:00:00.000Z',
    state: 'TN',
    location: 'Nashville',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/552.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-04-21T04:00:00.000Z',
    state: 'MD',
    location: 'Baltimore',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/530.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-04-28T04:00:00.000Z',
    state: 'FL',
    location: 'Tampa',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/560.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-05-19T04:00:00.000Z',
    state: 'FL',
    location: 'Sarasota',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/550.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-06-02T04:00:00.000Z',
    state: 'NJ',
    location: 'Morris Township',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/561.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-06-09T04:00:00.000Z',
    state: 'GA',
    location: 'Suwanee',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/548.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-06-16T04:00:00.000Z',
    state: 'PA',
    location: 'Philadelphia',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/557.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-06-23T04:00:00.000Z',
    state: 'FL',
    location: 'Coral Springs',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/536.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-07-07T04:00:00.000Z',
    state: 'MD',
    location: 'Baltimore',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/537.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-07-14T04:00:00.000Z',
    state: 'IL',
    location: 'Chicago',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/553.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-07-28T04:00:00.000Z',
    state: 'TN',
    location: 'Nashville',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/538.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-08-04T04:00:00.000Z',
    state: 'GA',
    location: 'Suwanee',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/544.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-08-18T04:00:00.000Z',
    state: 'NC',
    location: 'Charlotte',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/539.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-09-08T04:00:00.000Z',
    state: 'IL',
    location: 'Chicago',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/549.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-09-29T04:00:00.000Z',
    state: 'FL',
    location: 'Coral Springs',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/540.htm',
    type: 'Points',
  },
  {
    tournamentname: 'New Breed',
    date: '2018-10-27T04:00:00.000Z',
    state: 'SC',
    location: 'Columbia',
    price: 89,
    link: 'http://www.newbreedgear.com/NEWBREED_REGISTRATION_s/541.htm',
    type: 'Points',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-02-03T05:00:00.000Z',
    state: 'NY',
    location: 'New York Open',
    price: 69,
    link: 'http://www.goodfighttournament.com/new_york_open.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-02-10T05:00:00.000Z',
    state: 'OH',
    location: 'Youngstown Open',
    price: 49,
    link: 'http://www.goodfighttournament.com/youngstown_jiu_jitsu_open.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-02-17T05:00:00.000Z',
    state: 'FL',
    location: 'Battle at Fernandina Beach',
    price: 49,
    link: 'http://www.goodfighttournament.com/battle_at_fernandina_beach.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-02-24T05:00:00.000Z',
    state: 'NC',
    location: 'NC BJJ Championships',
    price: 49,
    link: 'http://www.goodfighttournament.com/nc_bjj_championships.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-03-10T05:00:00.000Z',
    state: 'PA',
    location: 'Tournament of Brotherly Love',
    price: 69,
    link:
      'http://www.goodfighttournament.com/tournament_of_brotherly_love.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-03-17T04:00:00.000Z',
    state: 'VA',
    location: 'Virginia BJJ Open',
    price: 49,
    link: 'http://www.goodfighttournament.com/virginia_bjj_open.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-04-07T04:00:00.000Z',
    state: 'SC',
    location: 'SC BJJ Classic',
    price: 49,
    link: 'http://www.goodfighttournament.com/sc_jiu_jitsu_classic.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-04-21T04:00:00.000Z',
    state: 'NY',
    location: 'New York State Championship',
    price: 69,
    link:
      'http://www.goodfighttournament.com/new_york_state_championships.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-04-28T04:00:00.000Z',
    state: 'NH',
    location: 'New Hampshire Championship',
    price: 69,
    link: 'http://www.goodfighttournament.com/new_hampshire_championship.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-05-05T04:00:00.000Z',
    state: 'DE',
    location: 'Duel at Delaware',
    price: 69,
    link: 'http://www.goodfighttournament.com/duel_at_delaware.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-05-19T04:00:00.000Z',
    state: 'NJ',
    location: 'Submission Only Pan Am 2018',
    price: 69,
    link: 'http://www.goodfighttournament.com/pan_ams.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-06-02T04:00:00.000Z',
    state: 'MD',
    location: 'Maryland Summer Classic',
    price: 69,
    link: 'http://www.goodfighttournament.com/maryland_summer_classic.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-06-23T04:00:00.000Z',
    state: 'TX',
    location: 'San Antonio Sub-Only Classic',
    price: 59,
    link: 'http://www.goodfighttournament.com/san_antonio_classic.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-06-16T04:00:00.000Z',
    state: 'MA',
    location: 'Boston Open',
    price: 69,
    link: 'http://www.goodfighttournament.com/boston_open.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-06-30T04:00:00.000Z',
    state: 'TN',
    location: 'Gatlinburg Invitational',
    price: 49,
    link: 'http://www.goodfighttournament.com/gatlinburg_invitational.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-07-14T04:00:00.000Z',
    state: 'PA',
    location: 'Philly Jiu Jitsu Challenge',
    price: 69,
    link: 'http://www.goodfighttournament.com/philly_jiu_jitsu_challenge.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-07-14T04:00:00.000Z',
    state: 'FL',
    location: 'Battle at Panama City',
    price: 49,
    link: 'http://www.goodfighttournament.com/battle_at_panama_city_beach.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-07-21T04:00:00.000Z',
    state: 'NY',
    location: 'New York Summer Classic',
    price: 69,
    link: 'http://www.goodfighttournament.com/ny_summer_classic.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'Good Fight',
    date: '2018-09-22T04:00:00.000Z',
    state: 'NJ',
    location: 'New Jersey Open',
    link: 'http://www.goodfighttournament.com/new_jersey_open.html',
    type: 'Submission Only',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-02-03T05:00:00.000Z',
    state: 'MD',
    location: 'US Grappling Maryland',
    price: 75,
    link: 'https://www.usgrappling.com/events/maryland-february-2018/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-02-23T05:00:00.000Z',
    state: 'NC',
    location: 'US Grappling Raleigh',
    price: 75,
    link: 'https://www.usgrappling.com/events/raleigh-march-2018/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-03-17T04:00:00.000Z',
    state: 'VA',
    location: 'US Grappling Virginia Beach',
    price: 75,
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-04-28T04:00:00.000Z',
    state: 'VA',
    location: 'US Grappling Richmond',
    price: 85,
    link: 'https://www.usgrappling.com/events/richmond-april-2018/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-05-05T04:00:00.000Z',
    state: 'NC',
    location: 'US Grappling Greesboro',
    link: 'https://www.usgrappling.com/events/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-07-14T04:00:00.000Z',
    state: 'NC',
    location: 'US Grappling Charlotte',
    link: 'https://www.usgrappling.com/events/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-07-28T04:00:00.000Z',
    state: 'VA',
    location: 'US Grappling Richmond',
    link: 'https://www.usgrappling.com/events/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-08-18T04:00:00.000Z',
    state: 'NC',
    location: 'Submission Only Raleigh',
    link: 'https://www.usgrappling.com/events/',
    type: 'Submission Only',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-09-28T04:00:00.000Z',
    state: 'PA',
    location: 'US Grappling PA',
    link: 'https://www.usgrappling.com/events/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-09-29T04:00:00.000Z',
    state: 'VA',
    location: 'US Grappling Virginia Beach',
    link: 'https://www.usgrappling.com/events/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-10-27T04:00:00.000Z',
    state: 'NC',
    location: 'US Grappling Greensboro',
    link: 'https://www.usgrappling.com/events/',
    type: 'Points',
  },
  {
    tournamentname: 'US Grappling',
    date: '2018-12-01T05:00:00.000Z',
    state: 'VA',
    location: 'Submission Only Richmond',
    link: 'https://www.usgrappling.com/events/',
    type: 'Submission Only',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-04-07T04:00:00.000Z',
    state: 'AZ',
    location: ' Grand Canyon State Open (Phoeonix, AZ)',
    price: 97,
    link: 'https://www.sjjif.com/public/eventInfo/202',
    type: 'Points',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-04-28T04:00:00.000Z',
    state: 'CA',
    location: 'Inland Empire Jiu Jitsu Open (Jurupa Valley, CA)',
    price: 97,
    link: 'https://www.sjjif.com/public/eventInfo/214',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-05-05T04:00:00.000Z',
    state: 'NV',
    location: 'Silver State International Jiu Jitsu Open (Las Vegas, NV)',
    price: 97,
    link: 'https://www.sjjif.com/public/eventInfo/220',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-05-19T04:00:00.000Z',
    state: 'CA',
    location: 'Northern California Jiu Jitsu Open (Oakland, CA)',
    price: 97,
    link: 'https://www.sjjif.com/public/eventInfo/193',
  },
  {
    tournamentname: 'NABJJF',
    date: '6/23-24/2018',
    state: 'CA',
    location: 'Los Angeles International Jiu Jitsu Open (Norwalk, CA)',
    price: 97,
    link: 'https://sjjif.com/public/eventInfo/238',
  },
  {
    tournamentname: 'NABJJF',
    date: '8/11-12/2018',
    state: 'CA',
    location: '14th Annual North American Tournament (Cerritos College, CA)',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-09-01T04:00:00.000Z',
    state: 'CA',
    location: 'Nationals Jiu Jitsu Tournament (San Diego, CA)',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-09-01T04:00:00.000Z',
    state: 'AZ',
    location: 'Phoenix Jiu Jitsu Open (Phoenix, AZ)',
  },
  {
    tournamentname: 'NABJJF',
    date: '10/26-28/2018',
    state: 'CA',
    location: 'SJJIF World Championship (Long Beach, CA)',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-11-01T04:00:00.000Z',
    state: 'CA',
    location: 'Golden State BJJ Open (Oakland, CA)',
  },
  {
    tournamentname: 'NABJJF',
    date: '2018-12-01T05:00:00.000Z',
    state: 'CA',
    location: 'Orange County International Open (Orange County, CA)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-04-21T04:00:00.000Z',
    state: 'MS',
    location: 'Jackson BJJ Championships (Jackson, MS)',
    price: 85,
    link:
      'http://www.americangrapplingfederation.com/event/2018-jackson-bjj-championships/',
  },
  {
    tournamentname: 'AGF',
    date: '2018-05-05T04:00:00.000Z',
    state: 'MO',
    location: 'Springfield BJJ Championships (Springfield, MO)',
    price: 85,
    link:
      'http://www.americangrapplingfederation.com/event/2018-springfield-bjj-championships/',
  },
  {
    tournamentname: 'AGF',
    date: '2018-05-12T04:00:00.000Z',
    state: 'TX',
    location: 'Dallas Spring Classic (Duncanville, TX)',
    price: 85,
    link:
      'http://www.americangrapplingfederation.com/event/2018-dallas-spring-classic/',
  },
  {
    tournamentname: 'AGF',
    date: '2018-05-19T04:00:00.000Z',
    state: 'OH',
    location: 'Columbus BJJ Championships (Columbus, OH)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-06-16T04:00:00.000Z',
    state: 'OK',
    location: 'Tulsa Open (Tulsa, OK)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-06-16T04:00:00.000Z',
    state: 'FL',
    location: 'Jacksonville BJJ Championships (Jacksonville, FL)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-06-23T04:00:00.000Z',
    state: 'LA',
    location: 'New Orleans BJJ Championships (Westwego, LA)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-06-30T04:00:00.000Z',
    state: 'AR',
    location: 'Arkansas Open (Conway, AR)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-07-07T04:00:00.000Z',
    state: 'VA',
    location: 'Virginia Beach Championships (Virginia Beach, VA)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-07-14T04:00:00.000Z',
    state: 'TX',
    location: 'San Antonio BJJ Championships (San Antonio, TX)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-07-28T04:00:00.000Z',
    state: 'AZ',
    location: 'Phoenix BJJ Championships (Scottsdale, AZ)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-08-04T04:00:00.000Z',
    state: 'TX',
    location: 'Houston Summer Classic (Houston, TX)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-08-11T04:00:00.000Z',
    state: 'KS',
    location: 'Kansas CIty BJJ Champioships (Kansas City, KS)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-09-08T04:00:00.000Z',
    state: 'MD',
    location: 'Marlyand BJJ Championships (Millersville, MD)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-09-08T04:00:00.000Z',
    state: 'GA',
    location: 'Atlanta BJJ Championships (Suwanee, GA)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-09-15T04:00:00.000Z',
    state: 'OK',
    location: 'Oklahoma City Open (Oklahoma City, OK)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-10-06T04:00:00.000Z',
    state: 'MO',
    location: 'St. Louis BJJ Championships (St. Louis, MO)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-10-13T04:00:00.000Z',
    state: 'NJ',
    location: 'Secaucus BJJ Championships (Secaucus, NJ)',
  },
  {
    tournamentname: 'AGF',
    date: '2017-10-20T04:00:00.000Z',
    state: 'AR',
    location: 'Arkansas State BJJ Championships (Conway, AR)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-10-27T04:00:00.000Z',
    state: 'TX',
    location: 'Dallas BJJ Championships (Duncanville, TX)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-12-15T05:00:00.000Z',
    state: 'OK',
    location: 'AGF Kids Nationals (Tulsa, OK)',
  },
  {
    tournamentname: 'AGF',
    date: '2018-12-16T05:00:00.000Z',
    state: 'OK',
    location: 'AGF Nationals (Tulsa, OK)',
  },
];
